spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    aws:
      region:
        static: eu-north-1
      credentials:
        access-key: AKIAVJR37NAMQ6RWCP63
        secret-key: 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

queue:
  notification: coinshift-notification-queue